### ISSUE TITLE
Add "button size" and "severity" option for  ActionButtonConfig..

### ISSUE THREAD

**Issue by shounak-dev** [itsmanwar/mh-prime-dynamic-table#6]
Add "button size" and "severity" option for  ActionButtonConfig..
e.g.
need button with option size and severity..
<p-button label="Small" icon="pi pi-check" size="small" severity="info"   />

**Comment by itsmanwar** [comment]
use PrimeNG button size class ```p-button-sm```

**Comment by itsmanwar** [comment]
use PrimeNG button size class ```p-button-sm```
